# Test containers
services:

  # Monitor machine
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    network_mode: host
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto-data:/mosquitto/data
      - ./mosquitto/mosquitto-log:/mosquitto/log
    restart: always

  monitor-service:
    build: ./monitor
    container_name: dashboard-monitor
    network_mode: host
    depends_on:
      - mqtt-broker
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    restart: always


  # Any other (myself or other PCs in the network)
  nginx-service:
    image: nginx:alpine
    container_name: Nginx_container
    hostname: hostname_do_docker
    ports:
      - "9999:9999/udp"  # reserved to agents
      - "8080:80"
    restart: always
    environment:
      - APP_ENV=testing
      - MONITORING_ENABLED=true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  agent-nginx:
    build: ./agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-service
    network_mode: "service:nginx-service" 
    container_name: agent-something-unique
    environment:
      - MY_CONTAINER_NAME=agent-something-unique
      - PYTHONUNBUFFERED=1 
